### ISSUE TITLE
Error: Cannot find module 'es6-promise\auto' 

### ISSUE THREAD

**Issue by berkandirim** [nuxt-community/pwa-template#9]
I'm getting the following error when I run `npm run dev`.

```
Error: Cannot find module 'es6-promise\auto' from 'C:\workspace\nuxt-pwa'
    at Function.module.exports [as sync] (C:\workspace\nuxt-pwa\node_modules\resolve\lib\sync.js:40:15)
    at r (C:\workspace\nuxt-pwa\node_modules\vue-server-renderer\build.js:7741:44)
    at Object.<anonymous> (webpack:/external "es6-promise/auto":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 2066bdea21510cb58403:25:0)
    at Object.<anonymous> (server-bundle.js:1440:75)
    at __webpack_require__ (webpack:/webpack/bootstrap 2066bdea21510cb58403:25:0)
    at Object.<anonymous> (server-bundle.js:996:65)
    at __webpack_require__ (webpack:/webpack/bootstrap 2066bdea21510cb58403:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (C:\workspace\nuxt-pwa\node_modules\vue-server-renderer\build.js:7747:21)
    at C:\workspace\nuxt-pwa\node_modules\vue-server-renderer\build.js:7805:18
    at C:\workspace\nuxt-pwa\node_modules\vue-server-renderer\build.js:7797:14
    at Object.renderToString (C:\workspace\nuxt-pwa\node_modules\vue-server-renderer\build.js:7951:9)
    at P (C:\workspace\nuxt-pwa\node_modules\pify\index.js:49:6)
    at Object.<anonymous> (C:\workspace\nuxt-pwa\node_modules\pify\index.js:11:9)
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c11">#c11</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. For the moment please install it using `yarn add es6-promise`. We will investigate this issue.
